dist: trusty
language: cpp
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - libboost-all-dev
script:
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir build 
  - cd build 
  - cmake ..
  - make
